# Generated by Django 2.0.7 on 2023-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('is_built', models.BooleanField(default=True)),
                ('gba', models.PositiveIntegerField(default=10000)),
                ('gla', models.PositiveIntegerField(default=9500)),
                ('owner', models.CharField(max_length=128)),
            ],
        ),
    ]
