# Generated by Django 4.1.7 on 2023-03-01 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(default='Блок 1', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('whs_area', models.PositiveIntegerField()),
                ('office_area', models.PositiveIntegerField()),
                ('mez_area', models.PositiveIntegerField()),
                ('lease_offered', models.BooleanField(default=True)),
                ('lease_whs_price', models.PositiveIntegerField()),
                ('lease_office_price', models.PositiveIntegerField()),
                ('lease_mez_price', models.PositiveIntegerField()),
                ('sale_offered', models.BooleanField(default=False)),
                ('sale_whs_price', models.PositiveIntegerField()),
                ('sale_office_price', models.PositiveIntegerField()),
                ('sale_mez_price', models.PositiveIntegerField()),
                ('_3pl_offered', models.BooleanField(default=False)),
                ('_3pl_price', models.PositiveIntegerField(null=True)),
                ('commercial_comment', models.CharField(max_length=256)),
                ('celling_height', models.PositiveSmallIntegerField()),
                ('column_grid', models.CharField(max_length=7)),
                ('floor_load', models.PositiveSmallIntegerField()),
                ('floor_type', models.CharField(max_length=20)),
                ('docks_amount', models.PositiveSmallIntegerField(null=True)),
                ('gates_amount', models.PositiveSmallIntegerField(null=True)),
                ('fire_system_type', models.CharField(max_length=32)),
                ('el_power', models.CharField(max_length=8)),
                ('heating', models.CharField(max_length=32)),
                ('cross_dock', models.BooleanField(default=False)),
                ('racks', models.BooleanField(default=False)),
                ('cathead', models.BooleanField(default=False)),
                ('tech_comment', models.TextField(max_length=256)),
                ('update', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Площадь',
                'verbose_name_plural': 'Площади',
            },
        ),
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=96)),
                ('ogrn', models.CharField(max_length=15)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=9)),
                ('legal_address', models.CharField(max_length=128)),
                ('post_address', models.CharField(max_length=128)),
                ('ceo', models.CharField(max_length=96)),
                ('bank_name', models.CharField(max_length=64)),
                ('p_account', models.CharField(max_length=20)),
                ('c_account', models.CharField(max_length=20)),
                ('bik', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Складской комплекс', 'Складской комплекс'), ('Производственный комплекс', 'Производственный комплекс'), ('Произодственно-складской комплекс', 'Произодственно-складской комплекс'), ('Логистический парк', 'Логистический парк'), ('Холодный склад', 'Холодный склад'), ('Крытая площадка', 'Крытая площадка'), ('Открытая площадка', 'Открытая площадка')], default='Складской комплекс', max_length=33)),
                ('name', models.CharField(max_length=64)),
                ('region', models.CharField(choices=[('Складской комплекc', 'Складской комплекc'), ('Производственный комплекс', 'Производственный комплекс'), ('Произодственно-складской комплекс', 'Произодственно-складской комплекс'), ('Логистический парк', 'Логистический парк'), ('Холодный склад', 'Холодный склад'), ('Крытая площадка', 'Крытая площадка'), ('Открытая площадка', 'Открытая площадка')], max_length=33)),
                ('highway', models.CharField(choices=[('Складской комплекс', 'Складской комплекс'), ('Производственный комплекс', 'Производственный комплекс'), ('Произодственно-складской комплекс', 'Произодственно-складской комплекс'), ('Логистический парк', 'Логистический парк'), ('Холодный склад', 'Холодный склад'), ('Крытая площадка', 'Крытая площадка'), ('Открытая площадка', 'Открытая площадка')], max_length=33)),
                ('location', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=256)),
                ('gba', models.PositiveIntegerField()),
                ('gla', models.PositiveIntegerField()),
                ('built_date', models.DateField(default=django.utils.timezone.now)),
                ('update', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='NT Properties', max_length=48)),
                ('landlord', models.BooleanField(default=True)),
                ('tenant', models.BooleanField(default=False)),
                ('agent', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.companycard')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
    ]
