# Generated by Django 4.1.7 on 2023-03-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_block__3pl_offered_alter_block__3pl_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='block',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='block',
            name='celling_height',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='block',
            name='column_grid',
            field=models.CharField(default='12 x 24', max_length=7),
        ),
        migrations.AlterField(
            model_name='block',
            name='docks_amount',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='el_power',
            field=models.CharField(default='200 кВт', max_length=8),
        ),
        migrations.AlterField(
            model_name='block',
            name='fire_system_type',
            field=models.CharField(choices=[('Спринклерная система пожаротушения', 'Спринклерная система пожаротушения'), ('Гидранты', 'Гидранты'), ('Огнетушители', 'Огнетушители'), ('Порошковая система пожаротушения', 'Порошковая система пожаротушения'), ('Специальная система пожаротушения', 'Специальная система пожаротушения')], default='Спринклерная система пожаротушения', max_length=34),
        ),
        migrations.AlterField(
            model_name='block',
            name='floor_load',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='block',
            name='gates_amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='block',
            name='heating',
            field=models.CharField(choices=[('Центральное отопление', 'Центральное отопление'), ('Собстенная котельная', 'Собстенная котельная'), ('Электрическое отопление', 'Электрическое отопление'), ('Воздушное отопление', 'Воздушное отопление'), ('Тёплый пол', 'Тёплый пол')], default='Центральное отопление', max_length=23),
        ),
        migrations.AlterField(
            model_name='block',
            name='lease_mez_price',
            field=models.PositiveIntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name='block',
            name='lease_office_price',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='block',
            name='sale_mez_price',
            field=models.PositiveIntegerField(default=35000),
        ),
        migrations.AlterField(
            model_name='block',
            name='sale_office_price',
            field=models.PositiveIntegerField(default=48000),
        ),
        migrations.AlterField(
            model_name='block',
            name='sale_whs_price',
            field=models.PositiveIntegerField(default=40000),
        ),
    ]
