# Generated by Django 4.1.7 on 2023-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_block_photo_block_plan_company_logo_property_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='card',
        ),
    ]
