# Generated by Django 4.1.7 on 2023-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_company_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='commercial_comment',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
