# Generated by Django 4.1.7 on 2023-03-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_company_industry_alter_block_commercial_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tenant',
            new_name='client',
        ),
    ]
