# Generated by Django 4.1.7 on 2023-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_block_photo_alter_block_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbmediaroot/block/photo'),
        ),
        migrations.AlterField(
            model_name='block',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='dbmediaroot/block/plan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dbmediaroot/property/photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='dbmediaroot/property/plan'),
        ),
    ]
