# Generated by Django 4.1.7 on 2023-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_block_photo_alter_block_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dbmediaroot/company/logo'),
        ),
    ]
