# Generated by Django 4.1.7 on 2023-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_block_photo_alter_block_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='block/plan'),
        ),
        migrations.AlterField(
            model_name='company',
            name='brand_name',
            field=models.CharField(max_length=48),
        ),
    ]
