# Generated by Django 4.1.7 on 2023-03-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_alter_block_plan_alter_company_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='_3pl_offered',
            new_name='log_offered',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='_3pl_price',
            new_name='log_price',
        ),
    ]
