# Generated by Django 4.1.7 on 2023-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_rename__3pl_offered_block_log_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='floor_level',
            field=models.FloatField(default=1.2),
        ),
        migrations.AddField(
            model_name='block',
            name='lease_avg_price',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='block',
            name='lease_total_price',
            field=models.PositiveIntegerField(default=7777),
        ),
        migrations.AddField(
            model_name='block',
            name='lease_vat_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='opex',
            field=models.PositiveIntegerField(default=1300),
        ),
        migrations.AddField(
            model_name='block',
            name='opex_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='sale_avg_price',
            field=models.PositiveIntegerField(default=32000),
        ),
        migrations.AddField(
            model_name='block',
            name='sale_total_price',
            field=models.PositiveIntegerField(blank=True, default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='sale_vat_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='temp_cond_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='temp_cond_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='fire_system_type',
            field=models.CharField(choices=[('Спринклерная система', 'Спринклерная система'), ('Гидранты', 'Гидранты'), ('Огнетушители', 'Огнетушители'), ('Порошковая система', 'Порошковая система'), ('Специальная система', 'Специальная система')], default='Спринклерная система пожаротушения', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='floor_type',
            field=models.CharField(choices=[('Бетон-антипыль', 'Бетон-антипыль'), ('Бетон', 'Бетон'), ('Бетонные плиты', 'Бетонные плиты'), ('Асфальт', 'Асфальт'), ('Заводская плитка', 'Заводская плитка')], default='Бетон-антипыль', max_length=16),
        ),
        migrations.AlterField(
            model_name='block',
            name='heating',
            field=models.CharField(choices=[('Центральное отопление', 'Центральное отопление'), ('Собственная котельная', 'Собственная котельная'), ('Электрическое отопление', 'Электрическое отопление'), ('Воздушное отопление', 'Воздушное отопление'), ('Тёплый пол', 'Тёплый пол')], default='Центральное отопление', max_length=23),
        ),
    ]
