# Generated by Django 4.1.7 on 2023-04-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_alter_block_celling_height_alter_block_docks_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='gba',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='kad_distance',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_latitude',
            field=models.CharField(default='55.750865', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='location_longitude',
            field=models.CharField(default='37.618752', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='fire_system_type',
            field=models.CharField(choices=[('Спринклерная система', 'Спринклерная система'), ('Гидранты', 'Гидранты'), ('Огнетушители', 'Огнетушители'), ('Порошковая система', 'Порошковая система'), ('Специальная система', 'Специальная система'), ('Нет', 'Нет')], default='Спринклерная система', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='gla',
            field=models.PositiveIntegerField(),
        ),
    ]
