# Generated by Django 4.1.7 on 2023-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_remove_property_gba_remove_property_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
